export enum ConditionTest {
  Cap = 'CAP',
  Floor = 'FLOOR',
  Range = 'RANGE',
  Equal = 'EQUAL',
  NotEqual = 'NOT EQUAL',
  In = 'IN',
  NotIn = 'NOT IN',
  Lt = 'LT',
  Gt = 'GT',
  Exists = 'EXISTS',
  DeepEqual = 'DEEPEQUAL',
  NotDeepEqual = 'NOT DEEPEQUAL',
  IsNull = 'IS NULL',
  IsNotNull = 'IS NOT NULL',
};
